// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyukQm-M_VKZB-4bXJO8tH9nGZuoEN64U',
    appId: '1:147699346754:web:ff899144f745e563b12cdb',
    messagingSenderId: '147699346754',
    projectId: 'appointment-booking-e27e8',
    authDomain: 'appointment-booking-e27e8.firebaseapp.com',
    storageBucket: 'appointment-booking-e27e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZckRS5iqn5WRqjUHgjZcGKUmfvZrjmoo',
    appId: '1:147699346754:android:165097c2db0b746eb12cdb',
    messagingSenderId: '147699346754',
    projectId: 'appointment-booking-e27e8',
    storageBucket: 'appointment-booking-e27e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJFAoOCnx5OVc5hx-mRFlJYNM7zhZR6w',
    appId: '1:147699346754:ios:92988367a3bac0f2b12cdb',
    messagingSenderId: '147699346754',
    projectId: 'appointment-booking-e27e8',
    storageBucket: 'appointment-booking-e27e8.firebasestorage.app',
    iosBundleId: 'com.example.appointmentBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJFAoOCnx5OVc5hx-mRFlJYNM7zhZR6w',
    appId: '1:147699346754:ios:92988367a3bac0f2b12cdb',
    messagingSenderId: '147699346754',
    projectId: 'appointment-booking-e27e8',
    storageBucket: 'appointment-booking-e27e8.firebasestorage.app',
    iosBundleId: 'com.example.appointmentBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyukQm-M_VKZB-4bXJO8tH9nGZuoEN64U',
    appId: '1:147699346754:web:ded2b0e1be475ec9b12cdb',
    messagingSenderId: '147699346754',
    projectId: 'appointment-booking-e27e8',
    authDomain: 'appointment-booking-e27e8.firebaseapp.com',
    storageBucket: 'appointment-booking-e27e8.firebasestorage.app',
  );
}
